# -*- coding: utf-8 -*-
"""sodiqova1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DvBwbztyj2Us-8K1fF6iw-TulIeuoZ1w
"""

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm= cv2.imread("izlash.jpg")
cv2_imshow(rasm)



qora= cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(qora)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread ("Bu shaharda hech kim yoq.jpg")
cv2_imshow(rasm)

qora= cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(qora)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread ("Sokinlik.jpg")
cv2_imshow(rasm)

qora= cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(qora)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread ("Kitob.jpg")
cv2_imshow(rasm)

qora= cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(qora)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread ("Rasm.jpg")
cv2_imshow(rasm)

qora= cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(qora)